###
GET http://localhost:5050/

###
GET http://localhost:5050/all-users/

###
POST http://localhost:5050/sign-up
Content-Type: application/json

{
    "username": "testUser",
    "password": "testPassword"
}