###
GET http://localhost:5050/

###
GET http://localhost:5050/blogs/2

###
GET http://localhost:5050/specific-blog

###
GET http://localhost:5050/all-users/

###
GET http://localhost:5050/all-blogs/

###
POST http://localhost:5050/sign-up
Content-Type: application/json

{
    "username": "testUser",
    "password": "testPassword"
}

###
POST http://localhost:5050/login
Content-Type: application/json

{
    "username": "testUser",
    "password": "testPW"
}